version: '3.1'

services:
  app:
    image: zakyfetoh/app-owais
    build: .
    container_name: app
    ports:
      - "80:3000"
    depends_on:
      - db

  prom: 
    image: prom/prometheus
    container_name: prom
    volumes:
      - ./prom-config:/etc/prometheus
    ports:
      -  9090:9090  

  grafana:
    image: grafana/grafana:7.1.5
    container_name: grafana
    ports:
      - 3000:3000


  db:
    container_name: owais-db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./sqlData:/var/lib/mysql
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080