apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-owais
spec:
  selector:
    matchLabels:
      app: app-owais
  template:
    metadata:
      labels:
        app: app-owais
    spec:
      containers:
      - name: app-owais
        image: zakyfetoh/app-owais
        env:
        - name: DB_HOST
          value: owais-db
        - name: DB_USER
          value: admin
        - name: DB_PASSWORD
          value: Go62Sc8^y#$#br45$g
        - name: DB_NAME
          value: owais
        - name: NUMBER_PER_PAGE
          value: "5"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: app-owais-service
spec:
  type: ClusterIP
  selector:
    app: app-owais
  ports:
  - port: 80
    targetPort: 3000
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: myapp
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app-owais
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: app-owais-pdb
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: app-owais